export const projects = [
    {
        index: "01",
        title: "AdTalk",
        subtitle: "an AI-powered marketing platform",
        media_file: "/adtalk/AdTalk.png",
        height_modifer: "1080/1920",
        layout: "text-right",
        // primary project page content
        page_type: "case study",
        url_name: "/adtalk",
        intro_text: "AdTalk is an AI-powered marketing platform that helps convenience store owners harness in-store interactions. ",
        blurb: "AdTalk allows distributors and convenience store owners to tap into the interactions between cashiers and customers and view product mentions, conversions, and other KPIs. This project aims to build a straightforward yet detailed dashboard for deployment, and prototype potential features to be added in future.",
        project_company: "Company: AdTalk",
        project_role: "Role: Product Designer",
        project_timeline: "Timeline: 3 months, Sep 2025 - Dec 2025",
        project_contributions: "Contributions: Wireframing, prototyping, visual design and branding, design system creation",
        caption: "Two primary features of the AdTalk dashboard - metrics and messaging.",
        elaboration: "My team built two flows for two user personas - the store owners and the distributors - based on competitive analysis by the product team. On top of collaboratively building prototypes, I created branding guidelines and built a simple design system by defining design tokens and creating reusable components, which streamlined both our team’s and the development team’s progress greatly.",
        //primary media
        hero_image: "/adtalk/AdTalk_hero.png",
        wide_image: "/adtalk/Adtalk_wide.png",
        //case study content
        problem_text: "Since AdTalk was an entirely new product, there was no existing dashboard or design guidelines. So, how might we design a clear, in-depth dashboard as an MVP, and build foundations for future teams to add and refine features while staying consistent with the brand?",
        research_text_1: "Given the limited time constraints of the project, our team opted to primarily work with the product team for research. They sent us competitors they found for their own research, and we evaluated these to identify necessary features, weak points to avoid, and the outline of our user flows. ",
        research_text_2: "Using results from the competitive analysis, we mapped out information architecture for our two primary users - the store operators and the distributors. Both were fairly similar - split between a dashboard page and a settings page - but it was important to record the differences in metrics and filters between the two.",
        iteration_text_1: "Using the information architecture, each team member sketched out wireframes that we would then merge into our low-fidelity.",
        iteration_text_2: "While building the low-fidelity prototype, I also worked on the branding and design system. I designed a logo with two variations, as well as defining color tokens and layout and typography guidelines.",
        iteration_text_3: "We were able to put the early version of the logo and design system into the low-fidelity to see how well it stood up. After several rounds of feedback, we moved into high-fidelity, switching out some metrics and colors, improving the logo, and after speaking to the founder added a couple new features for future deployment.",
        reflections_text: "This was my first time working on a B2B product, which required a bit of a shift for me. I learned to create easily legible data visualizations, as well as how to maintain usability and legibility without being able to compromise on detail. ",
        results_text: "Once we finished, the dashboard was handed off to the development team, who were able to build the MVP and deliver it to the founder. AdTalk is still being worked on, so I won’t be able to see the results until launch. However, our product was well received at the Texas Convergent Forge Showcase.",
        //case study media
        research_image_1: "/adtalk/Adtalk_competitive analysis.png",
        research_image_2: "/adtalk/AdTalk_IA.png",
        process_image_1: "/adtalk/AdTalk_sketches.png",
        process_image_2: "/adtalk/AdTalk_branding and design system.png",
        process_left_image: "/adtalk/AdTalk_process-left.png",
        process_right_image: "/adtalk/AdTalk_process-right.png",
        //style stuff
        page_layout: "wide",
        intro_text_color: "text-[#149DC1]",
        body_text_color: "text-[#373D47]",
        drop_text_color: "text-[#FFFFFF]",
        background_color: "bg-[#F1F5FA]",
        drop_bg_color: "bg-[#0277B6] fill-[#0277B6]",
        logo_color: "fill-[#0277B6]",
    },
    {
        index: "02",
        title: "Cradlelist",
        subtitle: "a marketplace for new and teen parents",
        media_file: "/Cradlelist/Cradlelist.png",
        height_modifer: "1080/1920",
        layout: "image-left",
        // project page stuff
        page_type: "case study",
        url_name: "/cradlelist",
        intro_text: "Cradlelist is a marketplace for teen and first-time parents.",
        blurb: "Cradlelist was designed for my Interaction Design class. For this project, I joined a team that tackled the subject of first-time and teen parents after the research phase. After conducting research and speaking to teen parents and social workers, my team discovered two key points - teen parents and social workers consistently rank financial support as an urgent need, and teen parents often lack community support. This project aims to create a design prototype that fills these gaps.",
        project_company: "School project",
        project_role: "Role: Product Designer",
        project_timeline: "Timeline: 2 weeks, Mar 2025 - Apr 2025",
        project_contributions: "Contributions: Wireframing, prototyping, visual design and branding, design system creation",
        caption: "Cradlelist’s main feature is the marketplace, where parents can buy or sell childcare items.",
        elaboration: "I built Cradlelist based on insights my team and I identified from my teammates’ research, prototyping the primary feature - the marketplace. In addition to making userflows and building the prototype, I also created a branding system and design tokens. This project was completed in a two-week sprint as part of a UX design course at UT Austin.",
        //primary media
        hero_image: "/Cradlelist/Cradlelist_Hero.png",
        wide_image: "/Cradlelist/Cradlelist_wide.png",
        //case study content
        problem_text: "Teen parents, on top of raising their children, often lack both financial and community support, which is important because they tend to turn to other parents for information about pregnancy and planning. How might we provide access to affordable child-rearing supplies for teen parents to alleviate financial stresses while offering access to a community of parents and childcare resources?",
        research_text_1: "Though I knew the project would only require prototyping one feature of the site, I wanted to thoroughly map out how all of the features would be used. For example, users might not just enter a marketplace site and start scrolling - being able to search, filter, and save listings or events was crucial. This step also helped me organize what exactly needed to be on each page, and how each microinteraction fit into the bigger picture.",
        iteration_text_1: "Based on the user flows, I created a concept page, including speculative use cases for two other devices. ",
        iteration_text_2: "I then started off with wireframing, basing my layout on pre-existing marketplace sites such as Craigslist or Ebay. ",
        iteration_text_3: "After wireframing, I also created branding assets and design tokens. I then took the work into Figma, swapping the forums idea out for a resources page that includes product safety recalls, parenting FAQs, and resources for teen parents, because a forum was outside the scope of the idea. I built out the full Marketplace flow, including viewing and creating sale posts.",
        reflections_text: "This project was my introduction to creating and working with design tokens and a design system, and my second project using user flows instead of information architecture maps as part of a user-focused design process. Design systems made my process much faster, and empathizing with the user while creating my user flows made the end product more accessible and approachable.",
        results_text: "My biggest takeaway from this project was thinking about community and how to shape how a community forms. Teen parents aren’t the only people who need and rely on community. As designers, the products we create can connect people, and thinking about community as a main feature rather than an afterthought allows a new pathway to empathize with our users. ",
        //case study media
        research_image_1: "/Cradlelist/Cradlelist_userflows.png",
        process_image_1: "/Cradlelist/Cradlelist_concept.png",
        process_image_2: "/Cradlelist/Cradlelist_sketches.png",
        process_left_image: "/Cradlelist/Cradlelist_left.png",
        process_right_image: "/Cradlelist/Cradlelist_right.png",
        //style stuff
        page_layout: "wide",
        intro_text_color: "text-[#6BBBC7]",
        body_text_color: "text-[#40454F]",
        drop_text_color: "text-[#FFFFFF]",
        background_color: "bg-[#fffbf1]",
        drop_bg_color: "bg-[#00cba3] fill-[#00cba3]",
        logo_color: "fill-[#00cba3]",
    },
    {
        index: "03",
        title: "Facebook Homepage Customization",
        subtitle: "a customizable redesign concept",
        media_file: "/Facebook/FB.png",
        height_modifer: "935/470",
        layout: "text-right",
        // project page stuff
        page_type: "case study",
        url_name: "/facebook-homepage-customization",
        intro_text: "A customizable redesign concept for Facebook's homepage features.",
        blurb: "This project was done for my Interaction Design class. My team chose to tackle the subject of older generations and social media. After interviewing Gen Xers and Boomers on their struggles with social media, my team and I pinpointed Facebook as the most commonly used social media, as well as a few pain points preventing older generations from using the platform smoothly. This project aims to build a feature prototype that declutters and better personalizes users’ experiences with the Facebook homepage.",
        project_company: "School project",
        project_role: "Role: UX Researcher, Product Designer",
        project_timeline: "Timeline: 2 months, Feb 2025 - Mar 2025",
        project_contributions: "Contributions: UX research, wireframing, prototyping",
        caption: "Users can choose the size of features and type of posts that appear on their homepage.",
        elaboration: "My team started by doing quantitative research on older generations’ social media use, then conducted interviews. We then split off and designed products based on our insights. I created user personas, mapped user flows, and then built the prototype.",
         //primary media
        hero_image: "/Facebook/FB_hero.png",
        wide_image: "/Facebook/FB_wide.png",
        //case study content
        problem_text: "Facebook can be frustrating to use. Crammed, cluttered interface elements lead to confusion, while prioritization of features such as Reels and Meta AI or algorithmically pushed content makes it more difficult for users to see what they want to see. How might we give users control over what they see on their Facebook homepages?",
        research_text_1: "In order to define a problem statement, my team first conducted a quantitative survey with 38 participants, then interviewed 9 survey participants, primarily focusing on Gen Xers and Baby Boomers.",
        research_text_2: "I created 3 user personas based on insights and traits that seemed to be associated with each other based on our interviews: Geoff, the bewildered browser; Carol, the jaded user; and Shannon, the captivated consumer. I based each persona’s pain points, thoughts, and behaviors on real quotes.",
        research_text_3: "I then created user flows for both desktop and mobile applications for a Facebook homepage customization feature. To better understand what the feature would do, I looked at the Facebook homepage and identified things that were mentioned by interviewees or that could contribute to a negative user experience. I also added a popup to the beginning of the flow when the user logs on for the first time after the feature is added, to ensure transparency about the feature’s existence and successful completion.",
        iteration_text_1: "I began with mid-fidelity key screens for both desktop and mobile, with very simple visuals, offering either a questionnaire or full customization.",
        iteration_text_2: "After a round of critique, I polished these key screens, made them more granular, and removed the questionnaire from the flow, as it was quite redundant and didn’t make the experience any more simple.",
        iteration_text_3: "I focused on the mobile flow while taking it into a hi-fi prototype, and polished it even further.",
        reflections_text: "This project allowed me to really get into the research side of things and go through the whole process from start to end. I found I especially enjoy pulling insights out of survey and interview responses and sorting them.",
        results_text: "My biggest takeaway from this project was the importance of empathy, and doing the legwork to gain that understanding. I personally don’t use Facebook, but after spending a couple months looking at social media through the lens of the people we interviewed, I’ve started noticing little things in the social media platforms I use that aren’t detrimental to my experience, but can and are for other people.",
        //case study media
        research_image_1: "/Facebook/FB_insights.png",
        research_image_2: "/Facebook/FB_personas.png",
        research_image_3: "/Facebook/FB_flows.png",
        process_image_1: "/Facebook/FB_process_1.png",
        process_image_2: "/Facebook/FB_process_2.png",
        process_left_image: "/Facebook/FB_process_left.png",
        process_right_image: "/Facebook/FB_process_right.png",
        //style stuff
        page_layout: "wide",
        intro_text_color: "text-[#0c2fd8]",
        body_text_color: "text-[#19255c]",
        background_color: "bg-[#FFFFFF]",
        drop_bg_color: "bg-[#0c2fd8] fill-[#0c2fd8]",
        logo_color: "fill-[#0c2fd8]",
    },
    {
        index: "04",
        title: "Exoterminal",
        subtitle: "a pixel typeface and game prototype",
        media_file: "/Exoterminal/Exoterminal.png",
        height_modifer: "393/480",
        layout: "image-left",
        // project page stuff
        page_type: "project overview",
        url_name: "/exoterminal",
        intro_text: "Exoterminal is a pixel typeface.",
        blurb: "Exoterminal’s almost serpentine curves give the otherwise nondescript typeface a distinctly alien feel, infusing simple letterforms with a slight edge.",
        caption: "Exoterminal includes both cases A-Z, numerals, and punctuation in two weights.",
        elaboration: "Inspired by retro 16-bit games, planets, and crabs, Exoterminal was designed for a game concept of the same name about spelling words as fast as possible to defeat a horde of extraterrestrial crustaceans. Because of the spelling mechanic, the typeface needed to be highly legible while maintaining an extraterrestrial feel. The end result marries a geometric form with parabolic arches inspired by the pincers of a crab.",
        hero_image: "/Exoterminal/Exoterminal_hero.png",
        left_image: "/Exoterminal/Exoterminal_left.png",
        right_image: "/Exoterminal/Exoterminal_right.png",
        process_left_image: "/Exoterminal/Exoterminal_processL.png",
        process_right_image: "/Exoterminal/Exoterminal_processR.png",
        //style stuff
        page_layout: "halfnhalf",
        intro_text_color: "text-[#c2f2b8]",
        body_text_color: "text-[#cad1c7]",
        drop_text_color: "text-[#000000]",
        drop_bg_color: "bg-[#cad1c7] fill-[#cad1c7]",
        background_color: "bg-[#000000]",
        logo_color: "fill-[#c2f2b8]",
    },
    {
        index: "05",
        title: "Rotun",
        subtitle: "a modular blackletter",
        media_file: "/Rotun/Rotun_VIDEO.mp4",
        height_modifer: "587/470",
        layout: "text-right",
        // project page stuff
        page_type: "project overview",
        url_name: "/rotun",
        intro_text: "Rotun is an exploration into modular blackletter.",
        blurb: "Designed for illegibility, Rotun’s towering spires and billowing strokes flirt with classic blackletter letterforms while toeing the line of comprehension. ",
        caption: "Rotun includes both cases A-Z, numerals, and punctuation.",
        elaboration: "Rotun was created for a conceptual prototype of a video game called Glyphdive, which explores the fine line between comprehensible and incomprehensible that type can walk. The process embraced modular construction to keep letterforms consistently abstract. A total of 15 discrete forms were assembled in various ways, forming motifs that echo across the letters, such as the twisting stems on both upper and lowercase letters, or an angular crescent forming the counters of round characters.",
        hero_image: "/Rotun/Rotun_hero.gif",
        wide_image: "/Rotun/Rotun_wide.png",
        process_left_image: "/Rotun/Rotun_left.png",
        process_right_image: "/Rotun/Rotun_right.png",
        //style stuff
        page_layout: "wide",
        intro_text_color: "text-[#cce0f4]",
        body_text_color: "text-[#FFFFFF]",
        drop_text_color: "text-[#000000]",
        background_color: "bg-[#000000]",
        drop_bg_color: "bg-[#cce0f4] fill-[#cce0f4]",
        logo_color: "fill-[#cce0f4]",
    },
    {
        index: "06",
        title: "Me when the meme got type in it",
        subtitle: "a study on typography and memes",
        media_file: "/me when the meme/Me_when_the_meme_got_type.png",
        height_modifer: "9/16",
        layout: "image-right",
        // project page stuff
        page_type: "project overview",
        url_name: "/me-when-the-meme-got-type-in-it",
        intro_text: 'A book that explores typography’s role in memes and what designers can learn from meme culture.',
        blurb: "Memes are everywhere — you probably have seen at least one today. They have increasingly shaped how people view and process culture and media, so why isn’t there more study about the design of memes? So, I researched, wrote, designed a layout, typeset, printed, and bound a book about it (stickers included).",
        caption: '"Me when the meme got type in it” has 3.5k words, 61 pages, 1 sticker sheet, and is the size of an iPhone 15 Pro Max.',
        elaboration: "Every aspect of the book - the massive top and bottom margins, the amount of text on each page, the full bleed meme collages interspersed throughout, and even the size and shape of the physical book - is designed to mimic the quick, almost brainless information flow of scrolling through a social media feed. “Bad” typefaces and styling and low-res images are intentionally placed to emphasize the highly democratized form of design that meme creation has become.",
        hero_image: "/me when the meme/Me_when_the_meme_hero.jpg",
        left_image: "/me when the meme/Me_when_the_meme_left.png",
        right_image: "/me when the meme/Me_when_the_meme_right.png",
        process_left_image: "/me when the meme/Me_when_the_meme_processL.png",
        process_right_image: "/me when the meme/Me_when_the_meme_processR.png",
        //style stuff
        page_layout: "thirds",
        intro_text_color: "text-[#000000]",
        body_text_color: "text-[#444444]",
        nav_text_color: "text-[#278eff]",
        drop_text_color: "text-[#ffffff]",
        background_color: "bg-[#ffffff]",
        drop_bg_color: "bg-[#278eff] fill-[#278eff]",
        logo_color: "fill-[#278eff]",
    },
    {
        index: "07",
        title: "Julie's Noodles",
        subtitle: "coupon card",
        media_file: "/julie's/Julies_Noodles.jpg",
        height_modifer: "420/470",
        layout: "text-left",
        // project page stuff
        page_type: "project overview",
        url_name: "/julies-noodles",
        intro_text: "A coupon card designed for Julie's Noodles, a local Austin restaurant and favorite of hungry UT students.",
        blurb: "This card was designed with memorability in mind, combining savory illustrations with crisp, playful typography to capture the eyes and stomachs of anyone holding the card and save it from wallet oblivion.",
        caption: "100 copies were printed and distributed to members of CSA.",
        elaboration: "When the Texas Chinese Student Association (CSA) approached Julie’s Noodles to create a language immersion program between students and the owner of the restaurant, part of the deal included a 10% coupon card. This design tantalizes the holder of the card, reminding them of the good conversation and even better food they had at Julie’s. ",
        hero_image: "/julie's/Julies_Noodles_hero.jpg",
        left_image: "/julie's/Julies_Noodles_left.png",
        right_image: "/julie's/Julies_Noodles_right.png",
        process_left_image: "/julie's/Julies_Noodles_processL.png",
        process_right_image: "/julie's/Julies_Noodles_processR.png",
        //style stuff
        page_layout: "halfnhalf",
        intro_text_color: "text-[#b34625]",
        body_text_color: "text-[#54130f]",
        drop_text_color: "text-[#fffbf1]",
        background_color: "bg-[#fffbf1]",
        drop_bg_color: "bg-[#b34625] fill-[#b34625]",
        logo_color: "fill-[#4d823c]",
    },
    // {
    //     index: "07",
    //     title: "Salt Lake City cultural souvenir",
    //     subtitle: "hidden gems and untold stories",
    //     media_file: "/souvenir/Souvenir_VIDEO.mp4",
    //     height_modifer: "626/470",
    //     layout: "image-left",
    //     url_name: "/salt-lake-city-cultural-souvenir",
    //     intro_text: "This is a souvenir prototype for Salt Lake City that encourages visitors to explore the less-known cultural richness of the city.",
    //     blurb: "Salt Lake City is best known as a predominantly white enclave for the Latter-Day Saints community and its snow sports. Less famous are its stories, spaces, and events created by thriving immigrant, BIPOC, and queer communities. I wanted to highlight these less-known aspects of the city, prototyping a blind box containing a figurine that spotlights an event or space within the city to explore. For the prototype, I focused on my own memories and experiences, but as a product, artists and designers around the city would be invited to contribute their own work to highlight a space or event of their choice.",
    //     hero_image: "/souvenir/Souvenir_hero.png",
    //     wide_image: "/souvenir/Souvenir_wide.png",
    //     left_image: "/souvenir/Souvenir_left.png",
    //     right_image: "/souvenir/Souvenir_right.png",
    //     process_left_image: "/julie's/Julies_Noodles_processL.png",
    //     process_right_image: "/julie's/Julies_Noodles_processR.png",
    //     page_layout: "halfnhalf",
    //     intro_text_color: "text-[#f15a29]",
    //     body_text_color: "text-[#366394]",
    //     background_color: "bg-[#fffbf1]",
    //     logo_color: "fill-[#fbae42]",
    // },
    // {
    //     index: "08",
    //     title: "Chinese Student Association social media",
    //     subtitle: "",
    //     media_file: "CSA_Instagram.jpg",
    //     height_modifer: "513/470",
    //     layout: "text-right",
    //     url_name: "/chinese-student-association-social-media-graphic-work",
    //     intro_text: "These graphics were created for the Texas Chinese Student Association Instagram page.",
    //     blurb: "As publicity director, I was responsible for designing eye-catching social media graphics to advertise events and merchandise, aiming to represent the spirit and mission of the organization while appealing to college students.",
    //     hero_image: "CSA_Instagram_hero.png",
    //     wide_image: "CSA_Instagram_wide.png",
    //     left_image: "CSA_Instagram_left.png",
    //     right_image: "CSA_Instagram_right.png",
    // },
    // {
    //     index: "09",
    //     title: "Chinese Student Association merch design",
    //     subtitle: "",
    //     media_file: "CSA_Merch.jpg",
    //     height_modifer: "470/470",
    //     layout: "image-left",
    //     url_name: "/chinese-student-association-merchandise-design",
    //     intro_text: "These items were designed for sale by the Texas Chinese Student Association.",
    //     blurb: "As publicity director, I was responsible for designing merch items such as stickers, shirts, and tote bags to raise funds. These items needed to represent the organization while also standing on their own as items students would be willing to pay for and wear/use. ",
    //     hero_image: "CSA_Merch_hero.png",
    //     wide_image: "CSA_Merch_wide.png",
    //     left_image: "CSA_Merch_left.png",
    //     right_image: "CSA_Merch_right.png",
    // },
    // {
    //     index: "10",
    //     title: "Backpack Soup",
    //     subtitle: "a game about getting ready",
    //     media_file: "Backpack_soup_VIDEO.mp4",
    //     height_modifer: "361/480",
    //     layout: "image-right",
    //     url_name: "/backpack-soup",
    //     intro_text: "Backpack soup is a game about the things you take with you every day.",
    //     blurb: "As a student, much of my life revolves around my backpack. So, an interaction I perform all the time is collect items into or take items out of my backpack. I explored the meaning of collecting items to sustain you throughout the day by making an absurd game about soup.",
    //     hero_image: "Backpack_soup_hero.png",
    //     wide_image: "Backpack_soup_wide.png",
    //     left_image: "Backpack_soup_left.png",
    //     right_image: "Backpack_soup_right.png",
    // }
];