export const projects = [
    {
        index: "01",
        title: "Cradlelist",
        subtitle: "a marketplace for new and teen parents",
        media_file: "Cradlelist_VIDEO.mp4",
        height_modifer: "1080/1920",
        layout: "image-left",
        url_name: "/cradlelist",
        intro_text: "Cradlelist is a marketplace for teen and first-time parents.",
        blurb: "Strollers, toys, books — you want the best for your kids, but that can get really expensive. Cradlelist provides a streamlined, user-friendly platform for buying and selling supplies for children at affordable prices. You can also find classes or activities near you, in case you want to brush up on childcare skills, take your child to an educational experience, or meet other parents and their families.",
        hero_image: "test_bkg.png",
        hero_height_modifier: "241/300",
        wide_image: "Cradlelist_wide.png",
        left_image: "Cradlelist_left.png",
        right_image: "Cradlelist_right.png",
        page_layout: "wide"
    },
    {
        index: "02",
        title: "Exoterminal",
        subtitle: "a pixel typeface and game prototype",
        media_file: "Exoterminal.png",
        height_modifer: "393/480",
        layout: "text-right",
        url_name: "/exoterminal",
        intro_text: "Exoterminal is a pixel typeface.",
        blurb: "Inspired by retro 16-bit games, planets, and crabs, Exoterminal was designed for a game concept of the same name involving spelling words as fast as possible to defeat an extraterrestrial horde of crustaceans.",
        hero_image: "Exoterminal_hero.png",
        wide_image: "Exoterminal_wide.png",
        left_image: "Exoterminal.png",
        right_image: "Exoterminal.png",
        page_layout: "thirds"
    },
    {
        index: "03",
        title: "Rotun",
        subtitle: "a modular blackletter",
        media_file: "Rotun_VIDEO.mp4",
        height_modifer: "587/470",
        layout: "image-left",
        url_name: "/rotun",
        intro_text: "Rotun is an exploration into modular blackletter.",
        blurb: "Designed for illegibility, Rotun was created for a conceptual prototype of a video game called Glyphdive, which explores the fine line between comprehensible and incomprehensible that type can walk.",
        hero_image: "Rotun_hero.png",
        wide_image: "Rotun_wide.png",
        left_image: "Rotun_left.png",
        right_image: "Rotun_right.png",
    },
    {
        index: "04",
        title: "Facebook custom homepage concept",
        subtitle: "",
        media_file: "Facebook_customization_flow.png",
        height_modifer: "935/470",
        layout: "image-right",
        url_name: "/facebook-homepage-customization",
        intro_text: "Facebook custom homepage is a redesign concept for Facebook's homepage features.",
        blurb: "By giving users the option to personalize and streamline their social media homepage, people of all ages, abilities, and backgrounds can experience Facebook without clutter or confusion.",
        hero_image: "Facebook_customization_hero.png",
        wide_image: "Facebook_customization_wide.png",
        left_image: "Facebook_customization_left.png",
        right_image: "Facebook_customization_right.png",
    },
    {
        index: "05",
        title: "Me when the meme got type in it",
        subtitle: "a study on typography and memes",
        media_file: "Me_when_the_meme_got_type.png",
        height_modifer: "831/480",
        layout: "text-left",
        url_name: "/me-when-the-meme-got-type-in-it",
        intro_text: '"Me when the meme got type in it” explores typography’s use in memes and what designers can learn from meme culture.',
        blurb: "Memes are everywhere — you probably have seen at least one today. They have increasingly shaped how people view and process culture and media, so why isn’t there more study about the design of memes? So, I researched, wrote, designed a layout, typeset, printed, and bound a book about it (stickers included).",
        hero_image: "Me_when_the_meme_hero.png",
        wide_image: "Me_when_the_meme_wide.png",
        left_image: "Me_when_the_meme_left.png",
        right_image: "Me_when_the_meme_right.png",
    },
    {
        index: "06",
        title: "Julie's Noodles",
        subtitle: "coupon card",
        media_file: "Julies_Noodles.jpg",
        height_modifer: "420/470",
        layout: "image-right",
        url_name: "/julies-noodles",
        intro_text: "This coupon card was designed for Julie's Noodles, a local Austin restaurant and favorite of hungry UT students.",
        blurb: "When the Texas Chinese Student Association (CSA) approached Julie’s Noodles to create a language immersion program between students and the owner of the restaurant, part of the deal included a 10% coupon card. This design tantalizes the holder of the card, reminding them of the good conversation and even better food they had at Julie’s.",
        hero_image: "Julies_Noodles_hero.png",
        wide_image: "Julies_Noodles_wide.png",
        left_image: "Julies_Noodles_left.png",
        right_image: "Julies_Noodles_right.png",
    },
    {
        index: "07",
        title: "Salt Lake City cultural souvenir",
        subtitle: "hidden gems and untold stories",
        media_file: "Souvenir_VIDEO.mp4",
        height_modifer: "626/470",
        layout: "image-left",
        url_name: "/salt-lake-city-cultural-souvenir",
        intro_text: "This is a souvenir prototype for Salt Lake City that encourages visitors to explore the less-known cultural richness of the city.",
        blurb: "Salt Lake City is best known as a predominantly white enclave for the Latter-Day Saints community and its snow sports. Less famous are its stories, spaces, and events created by thriving immigrant, BIPOC, and queer communities. I wanted to highlight these less-known aspects of the city, prototyping a blind box containing a figurine that spotlights an event or space within the city to explore. For the prototype, I focused on my own memories and experiences, but as a product, artists and designers around the city would be invited to contribute their own work to highlight a space or event of their choice.",
        hero_image: "Souvenir_hero.png",
        wide_image: "Souvenir_wide.png",
        left_image: "Souvenir_left.png",
        right_image: "Souvenir_right.png",
    },
    {
        index: "08",
        title: "Chinese Student Association social media",
        subtitle: "",
        media_file: "CSA_Instagram.jpg",
        height_modifer: "513/470",
        layout: "text-right",
        url_name: "/chinese-student-association-social-media-graphic-work",
        intro_text: "These graphics were created for the Texas Chinese Student Association Instagram page.",
        blurb: "As publicity director, I was responsible for designing eye-catching social media graphics to advertise events and merchandise, aiming to represent the spirit and mission of the organization while appealing to college students.",
        hero_image: "CSA_Instagram_hero.png",
        wide_image: "CSA_Instagram_wide.png",
        left_image: "CSA_Instagram_left.png",
        right_image: "CSA_Instagram_right.png",
    },
    {
        index: "09",
        title: "Chinese Student Association merch design",
        subtitle: "",
        media_file: "CSA_Merch.jpg",
        height_modifer: "470/470",
        layout: "image-left",
        url_name: "/chinese-student-association-merchandise-design",
        intro_text: "These items were designed for sale by the Texas Chinese Student Association.",
        blurb: "As publicity director, I was responsible for designing merch items such as stickers, shirts, and tote bags to raise funds. These items needed to represent the organization while also standing on their own as items students would be willing to pay for and wear/use. ",
        hero_image: "CSA_Merch_hero.png",
        wide_image: "CSA_Merch_wide.png",
        left_image: "CSA_Merch_left.png",
        right_image: "CSA_Merch_right.png",
    },
    {
        index: "10",
        title: "Backpack Soup",
        subtitle: "a game about getting ready",
        media_file: "Backpack_soup_VIDEO.mp4",
        height_modifer: "361/480",
        layout: "image-right",
        url_name: "/backpack-soup",
        intro_text: "Backpack soup is a game about the things you take with you every day.",
        blurb: "As a student, much of my life revolves around my backpack. So, an interaction I perform all the time is collect items into or take items out of my backpack. I explored the meaning of collecting items to sustain you throughout the day by making an absurd game about soup.",
        hero_image: "Backpack_soup_hero.png",
        wide_image: "Backpack_soup_wide.png",
        left_image: "Backpack_soup_left.png",
        right_image: "Backpack_soup_right.png",
    }
];