export const projects = [
    {
        index: "01",
        title: "Cradlelist",
        subtitle: "a marketplace for new and teen parents",
        media_file: "Cradlelist_VIDEO.mp4",
        height_modifer: "1080/1920",
        layout: "image-left",
        url_name: "/cradlelist",
        intro_text: "Cradlelist is a marketplace for teen and first-time parents to buy and sell childcare items, and find classes and kid-friendly events.",
        blurb: "Strollers, toys, books — you want the best for your kids, but sometimes that gets really expensive. Cradlelist provides a streamlined, user-friendly platform for buying and selling supplies for children at affordable prices. You can also find classes or activities near you, in case you want to brush up on childcare skills, take your child to an educational experience, or meet other parents and their families.",
        hero_image: "test_bkg.png",
        hero_height_modifier: "241/300",
        wide_image: "Cradlelist_wide.png",
        left_image: "Cradlelist_left.png",
        right_image: "Cradlelist_right.png",
    },
    {
        index: "02",
        title: "Exoterminal",
        subtitle: "a pixel typeface and game prototype",
        media_file: "Exoterminal.png",
        height_modifer: "393/480",
        layout: "text-right",
        url_name: "/exoterminal",
        intro_text: "Exoterminal - a pixel typeface and game prototype",
        blurb: "",
        hero_image: "Exoterminal_hero.png",
        wide_image: "Exoterminal_wide.png",
        left_image: "Exoterminal_left.png",
        right_image: "Exoterminal_right.png",
    },
    {
        index: "03",
        title: "Rotun",
        subtitle: "a modular blackletter",
        media_file: "Rotun_VIDEO.mp4",
        height_modifer: "587/470",
        layout: "image-left",
        url_name: "/rotun",
        intro_text: "Rotun - a modular blackletter",
        blurb: "Rotun is an exploration into modular blackletter inspired by Rotunda script and the work of Marian Bantjes. Designed for illegibility, Rotun was created for a conceptual prototype of a video game called Glyphdive, which explores the fine line between comprehensible and incomprehensible that type can walk.",
        hero_image: "Rotun_hero.png",
        wide_image: "Rotun_wide.png",
        left_image: "Rotun_left.png",
        right_image: "Rotun_right.png",
    },
    {
        index: "04",
        title: "Facebook homepage customization concept",
        subtitle: "",
        media_file: "Facebook_customization_flow.png",
        height_modifer: "935/470",
        layout: "image-right",
        url_name: "/facebook-homepage-customization",
        intro_text: "Facebook homepage customization - a redesign concept for Facebook's homepage customization features",
        blurb: "",
        hero_image: "Facebook_customization_hero.png",
        wide_image: "Facebook_customization_wide.png",
        left_image: "Facebook_customization_left.png",
        right_image: "Facebook_customization_right.png",
    },
    {
        index: "05",
        title: "Me when the meme got type in it",
        subtitle: "a study on typography and memes",
        media_file: "Me_when_the_meme_got_type.png",
        height_modifer: "831/480",
        layout: "text-left",
        url_name: "/me-when-the-meme-got-type-in-it",
        intro_text: '"Me when the meme got type in it" - a study on typography and memes',
        blurb: "",
        hero_image: "Me_when_the_meme_hero.png",
        wide_image: "Me_when_the_meme_wide.png",
        left_image: "Me_when_the_meme_left.png",
        right_image: "Me_when_the_meme_right.png",
    },
    {
        index: "06",
        title: "Julie's Noodles",
        subtitle: "coupon card",
        media_file: "Julies_Noodles.jpg",
        height_modifer: "420/470",
        layout: "image-right",
        url_name: "/julies-noodles",
        intro_text: "Julie's Noodles - a coupon card",
        blurb: "",
        hero_image: "Julies_Noodles_hero.png",
        wide_image: "Julies_Noodles_wide.png",
        left_image: "Julies_Noodles_left.png",
        right_image: "Julies_Noodles_right.png",
    },
    {
        index: "07",
        title: "Salt Lake City cultural souvenir",
        subtitle: "hidden gems and untold stories",
        media_file: "Souvenir_VIDEO.mp4",
        height_modifer: "626/470",
        layout: "image-left",
        url_name: "/salt-lake-city-cultural-souvenir",
        intro_text: "Salt Lake City cultural souvenir - hidden gems and untold stories",
        blurb: "",
        hero_image: "Souvenir_hero.png",
        wide_image: "Souvenir_wide.png",
        left_image: "Souvenir_left.png",
        right_image: "Souvenir_right.png",
    },
    {
        index: "08",
        title: "Fishbowl",
        subtitle: "an open house for tiny homes",
        media_file: "Fishbowl.jpg",
        height_modifer: "696/480",
        layout: "text-right",
        url_name: "/fishbowl",
        intro_text: "Fishbowl - an open house for tiny homes",
        blurb: "",
        hero_image: "Fishbowl_hero.png",
        wide_image: "Fishbowl_wide.png",
        left_image: "Fishbowl_left.png",
        right_image: "Fishbowl_right.png",
    },
    {
        index: "09",
        title: "Chinese Student Association",
        subtitle: "social media graphic work",
        media_file: "CSA_Instagram.jpg",
        height_modifer: "513/470",
        layout: "image-left",
        url_name: "/chinese-student-association-social-media-graphic-work",
        intro_text: "Chinese Student Association - social media graphic work",
        blurb: "",
        hero_image: "CSA_Instagram_hero.png",
        wide_image: "CSA_Instagram_wide.png",
        left_image: "CSA_Instagram_left.png",
        right_image: "CSA_Instagram_right.png",
    },
    {
        index: "10",
        title: "Chinese Student Association",
        subtitle: "merchandise design",
        media_file: "CSA_Merch.jpg",
        height_modifer: "470/470",
        layout: "image-right",
        url_name: "/chinese-student-association-merchandise-design",
        intro_text: "Chinese Student Association - merchandise design",
        blurb: "",
        hero_image: "CSA_Merch_hero.png",
        wide_image: "CSA_Merch_wide.png",
        left_image: "CSA_Merch_left.png",
        right_image: "CSA_Merch_right.png",
    },
    {
        index: "11",
        title: "Backpack Soup",
        subtitle: "a game about getting ready",
        media_file: "Backpack_soup_VIDEO.mp4",
        height_modifer: "361/480",
        layout: "text-left",
        url_name: "/backpack-soup",
        intro_text: "Backpack Soup - a game about getting ready",
        blurb: "",
        hero_image: "Backpack_soup_hero.png",
        wide_image: "Backpack_soup_wide.png",
        left_image: "Backpack_soup_left.png",
        right_image: "Backpack_soup_right.png",
    },
    {
        index: "12",
        title: "Magic Mountain",
        subtitle: "Fortlandia playground concept",
        media_file: "Magic_Mountain.png",
        height_modifer: "576/470",
        layout: "image-right",
        url_name: "/magic-mountain",
        intro_text: "Magic Mountain - Fortlandia playground concept",
        blurb: "",
        hero_image: "Magic_Mountain_hero.png",
        wide_image: "Magic_Mountain_wide.png",
        left_image: "Magic_Mountain_left.png",
        right_image: "Magic_Mountain_right.png",
    },
    {
        index: "13",
        title: "Rockin' Out with the Flairs",
        subtitle: "",
        media_file: "Flairs_poster.png",
        height_modifer: "611/470",
        layout: "image-left",
        url_name: "/rockin-out-with-the-flairs",
        intro_text: "Rockin' Out with the Flairs",
        blurb: "",
        hero_image: "Flairs_poster_hero.png",
        wide_image: "Flairs_poster_wide.png",
        left_image: "Flairs_poster_left.png",
        right_image: "Flairs_poster_right.png",
    },
];